### PR TITLE
Enhancement: Use jgt_tools

### PR DESCRIPTION
**Pull request by brolewis**
Migrate from maintained scripts to JGT Tools.

### CODE REVIEW

**Review by bradsbrown — APPROVED** [review]
Good grief, I love how much this cleans things up

**Review by dgou — COMMENTED** [review]
I think this PR is going to be obsolete when PR #30 lands in JGT_Tools?

**Comment by dgou** [comment]
So I pulled this PR, set up a fresh venv, ran bootstrap.
```
$ self-check 
+poetry run pre-commit run -a
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-mypy.
[INFO] Installing environment for https://github.com/pre-commit/mirrors-mypy.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
black....................................................................Passed
flake8...................................................................Passed
mypy.....................................................................Passed
71fb96240a4acca 
1597174796 15:39:56
505 ~/code/jiratools
$ run-tests 
+poetry run python -m pytest -vvv
/home/dgou/.virtual_envs/71fb96240a4acca/bin/python: No module named pytest
```

**Review by dgou — APPROVED** [review]
LGTM.
There are no self-tests for this, so when I use the `run-tests` entry-point I get a clean, but useless run.

**Pull request merged**
