### PR TITLE
jiratools: Add assign issue

### PR DESCRIPTION
**Pull request by ecedmondson**
This is a first draft but I had an idea about something and I wanted to check in the pypi JIRA package before I'm ready to ask for a commit.

Feel free to review this so far if you have the time but no worries.

### CODE REVIEW

**Comment by ecedmondson** [comment]
This should be ready now that I've removed the test data via force push.

**Review by bradsbrown — CHANGES_REQUESTED** [review]
This looks great! If you’ll add a version bump, I can merge.

**Comment by ecedmondson** [comment]
Well that was a silly thing to forget. On it!

**Comment by bradsbrown** [comment]
Going to go ahead and merge this, then do a version bump separately so I can get this updated and moved over to `jolly-good-toolbelt`

**Comment by ecedmondson** [comment]
Good idea.

**Pull request merged**
